$(document).ready(function(){
  $("#cycle_of_new_themes").click(function(){
	$("#comic").attr("src","pics/comics/standalone/cycle_of_new_themes_big.jpg");
  });
  $("#instructions").click(function(){
	$("#comic").attr("src","pics/comics/standalone/instructions_comic.jpg");
  });
  $("#video_games").click(function(){
	$("#comic").attr("src","pics/comics/standalone/video_games_comic_ver_2.jpg");
  });
  $("#stepping_on_bricks").click(function(){
	$("#comic").attr("src","pics/comics/standalone/comic_stepping_on_bricks.jpg");
  });
  $("#secure_your_load").click(function(){
	$("#comic").attr("src","pics/comics/standalone/secure_your_load_concept_3.jpg");
  });
  $("#talk_like_a_pirate_day").click(function(){
	$("#comic").attr("src","pics/comics/standalone/Talk_like_a_Pirate_Day_2013.jpg");
  });
  $("#trick-or-treating").click(function(){
	$("#comic").attr("src","pics/comics/standalone/Brick Comic I got a rock.jpg");
  });
});